import React from 'react';
import { Container, Typography, Box } from '@mui/material';
import BalanceSheetTable from './components/BalanceSheetTable';
import { BalanceSheetRow } from './types';

const balanceSheetData: BalanceSheetRow[] = [
  {
    id: 'activa',
    label: 'ACTIVA',
    code: '20/58',
    level: 0,
    isCollapsible: true,
    isTotal: true,
    years: [0, 0, 0, 0, 0],
    children: [
      {
        id: 'oprichtingskosten',
        label: 'I. Oprichtingskosten',
        code: '20',
        level: 1,
        isCollapsible: false,
        isTotal: false,
        years: [0, 0, 0, 0, 0],
      },
      {
        id: 'vaste-activa',
        label: 'VASTE ACTIVA',
        code: '21/28',
        level: 1,
        isCollapsible: true,
        isTotal: true,
        years: [0, 0, 0, 0, 0],
        children: [
          {
            id: 'immateriele-vaste-activa',
            label: 'II. Immateriële vaste activa',
            code: '21',
            level: 2,
            isCollapsible: false,
            isTotal: false,
            years: [0, 0, 0, 0, 0],
          },
          {
            id: 'materiele-vaste-activa',
            label: 'III. Materiële vaste activa',
            code: '22/27',
            level: 2,
            isCollapsible: true,
            isTotal: true,
            years: [0, 0, 0, 0, 0],
            children: [
              {
                id: 'terreinen',
                label: 'A. Terreinen en gebouwen',
                code: '22',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [125000.50, 135000.75, 142500.25, 138750.80, 145000.60],
              },
              {
                id: 'installaties',
                label: 'B. Installaties, machines en uitrusting',
                code: '23',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [75000.25, 82500.50, 88750.75, 85000.40, 92500.30],
              },
              {
                id: 'meubilair',
                label: 'C. Meubilair en rollend materiëel',
                code: '24',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [25000.75, 27500.25, 29750.50, 28500.60, 31000.20],
              },
              {
                id: 'leasing',
                label: 'D. Leasing en soortgelijke rechten',
                code: '25',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [0, 0, 0, 0, 0],
              },
              {
                id: 'overige-materiele',
                label: 'E. Overige materiële vaste activa',
                code: '26',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [0, 0, 0, 0, 0],
              },
              {
                id: 'activa-in-aanbouw',
                label: 'F. Activa in aanbouw en vooruitbetalingen',
                code: '27',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [0, 0, 0, 0, 0],
              },
            ],
          },
          {
            id: 'financiele-vaste-activa',
            label: 'IV. Financiële vaste activa',
            code: '28',
            level: 2,
            isCollapsible: true,
            isTotal: true,
            years: [0, 0, 0, 0, 0],
            children: [
              {
                id: 'verbonden-ondernemingen',
                label: 'A. Verbonden ondernemingen',
                code: '280/1',
                level: 3,
                isCollapsible: true,
                isTotal: true,
                years: [0, 0, 0, 0, 0],
                children: [
                  {
                    id: 'deelnemingen-1',
                    label: '1. Deelnemingen',
                    code: '280',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                  {
                    id: 'vorderingen-1',
                    label: '2. Vorderingen',
                    code: '281',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                ],
              },
              {
                id: 'deelnemingsverhouding',
                label: 'B. Ondern. waarmee een deelnemingsverhouding bestaat',
                code: '282/3',
                level: 3,
                isCollapsible: true,
                isTotal: true,
                years: [0, 0, 0, 0, 0],
                children: [
                  {
                    id: 'deelnemingen-2',
                    label: '1. Deelnemingen',
                    code: '282',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                  {
                    id: 'vorderingen-2',
                    label: '2. Vorderingen',
                    code: '283',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                ],
              },
              {
                id: 'andere-financiele-activa',
                label: 'C. Andere financiële vaste activa',
                code: '284/8',
                level: 3,
                isCollapsible: true,
                isTotal: true,
                years: [0, 0, 0, 0, 0],
                children: [
                  {
                    id: 'aandelen',
                    label: '1. Aandelen',
                    code: '284',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                  {
                    id: 'vorderingen-en-borgtochten',
                    label: '2. Vorderingen en borgtochten in contanten',
                    code: '285/8',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 'vlottende-activa',
        label: 'VLOTTENDE ACTIVA',
        code: '29/58',
        level: 1,
        isCollapsible: true,
        isTotal: true,
        years: [0, 0, 0, 0, 0],
        children: [
          {
            id: 'vorderingen-meer-dan-1-jaar',
            label: 'V. Vorderingen op meer dan één jaar',
            code: '29',
            level: 2,
            isCollapsible: true,
            isTotal: true,
            years: [0, 0, 0, 0, 0],
            children: [
              {
                id: 'handelsvorderingen-1',
                label: 'A. Handelsvorderingen',
                code: '290',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [0, 0, 0, 0, 0],
              },
              {
                id: 'overige-vorderingen-1',
                label: 'B. Overige vorderingen',
                code: '291',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [0, 0, 0, 0, 0],
              },
            ],
          },
          {
            id: 'voorraden',
            label: 'VI. Voorraden en bestellingen in uitvoering',
            code: '3',
            level: 2,
            isCollapsible: true,
            isTotal: true,
            years: [0, 0, 0, 0, 0],
            children: [
              {
                id: 'voorraden-detail',
                label: 'A. Voorraden',
                code: '30/36',
                level: 3,
                isCollapsible: true,
                isTotal: true,
                years: [0, 0, 0, 0, 0],
                children: [
                  {
                    id: 'grond-en-hulpstoffen',
                    label: '1. Grond- en hulpstoffen',
                    code: '30/31',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                  {
                    id: 'goederen-in-bewerking',
                    label: '2. Goederen in bewerking',
                    code: '32',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                  {
                    id: 'gereed-product',
                    label: '3. Gereed product',
                    code: '33',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                  {
                    id: 'handelsgoederen',
                    label: '4. Handelsgoederen',
                    code: '34',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                  {
                    id: 'onroerende-goederen',
                    label: '5. Onroerende goederen bestemd voor verkoop',
                    code: '35',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                  {
                    id: 'vooruitbetalingen',
                    label: '6. Vooruitbetalingen',
                    code: '36',
                    level: 4,
                    isCollapsible: false,
                    isTotal: false,
                    years: [0, 0, 0, 0, 0],
                  },
                ],
              },
              {
                id: 'bestellingen-in-uitvoering',
                label: 'B. Bestellingen in uitvoering',
                code: '37',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [0, 0, 0, 0, 0],
              },
            ],
          },
          {
            id: 'vorderingen-ten-hoogste-1-jaar',
            label: 'VII. Vorderingen op ten hoogste één jaar',
            code: '40/41',
            level: 2,
            isCollapsible: true,
            isTotal: true,
            years: [0, 0, 0, 0, 0],
            children: [
              {
                id: 'handelsvorderingen-2',
                label: 'A. Handelsvorderingen',
                code: '40',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [0, 0, 0, 0, 0],
              },
              {
                id: 'overige-vorderingen-2',
                label: 'B. Overige vorderingen',
                code: '41',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [0, 0, 0, 0, 0],
              },
            ],
          },
          {
            id: 'geldbeleggingen',
            label: 'VIII. Geldbeleggingen',
            code: '50/53',
            level: 2,
            isCollapsible: true,
            isTotal: true,
            years: [0, 0, 0, 0, 0],
            children: [
              {
                id: 'eigen-aandelen',
                label: 'A. Eigen aandelen',
                code: '50',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [0, 0, 0, 0, 0],
              },
              {
                id: 'overige-beleggingen',
                label: 'B. Overige beleggingen',
                code: '51/53',
                level: 3,
                isCollapsible: false,
                isTotal: false,
                years: [0, 0, 0, 0, 0],
              },
            ],
          },
          {
            id: 'liquide-middelen',
            label: 'IX. Liquide middelen',
            code: '54/58',
            level: 2,
            isCollapsible: false,
            isTotal: false,
            years: [0, 0, 0, 0, 0],
          },
          {
            id: 'overlopende-rekeningen',
            label: 'X. Overlopende rekeningen',
            code: '490/1',
            level: 2,
            isCollapsible: false,
            isTotal: false,
            years: [0, 0, 0, 0, 0],
          },
        ],
      },
    ],
  },
];

function App() {
  return (
    <Container maxWidth={false} sx={{ maxWidth: 1600 }}>
      <Box sx={{ my: 4 }}>
        <Typography variant="h4" component="h1" gutterBottom>
          Balance Sheet
        </Typography>
        <BalanceSheetTable data={balanceSheetData} />
      </Box>
    </Container>
  );
}

export default App; 